### ISSUE TITLE
'Find asset URL' does not work when ' are contained in json

### ISSUE THREAD

**Issue by Clindbergh** [noobient/ansible-galaxy-github_release#2]
Example: The [CMAK](https://github.com/yahoo/CMAK/releases/tag/3.0.0.6) contains the string _What's changed_. The jq expression now fails because the json input is terminated early.

**Comment by bviktor** [comment]
Hey, thanks a lot for reporting! And also for the PR.

TIL there's a `quote` filter in Jinja2, it seems to be the 100% correct solution, so I decided to go with that route.

Also please note that I'm in the middle of transitioning my Galaxy roles to consistent return value "namespaces" (for the lack of better word), so the return value changed from `github_release_url` to `github_release.url`, sorry for the inconvenience this may have caused, but it should be better in the long run, coz all the roles will have proper namespaces and their attributes within, instead of randomly made-up, overly long variable names.

I also extended the tests to use this CMAK example, great find indeed. Who would've expected a ' in the changelog will cause an error lol.

**Comment by Clindbergh** [comment]
Thanks for the quick response and merge!

> TIL there's a quote filter in Jinja2

Nice, I wasn't aware of the quote filter :+1: 

> Also please note that I'm in the middle of transitioning my Galaxy roles to consistent return value "namespaces"

That seems reasonable. Perhaps it would be a good ideas to add [semantic versioning](https://semver.org/) tags to this repository so such changes could be identified as breaking changes.
